let lang = {
  en: {
    Technical: "TECHNICAL",
    operating: "FOR OPERATING AND SUPPLYING METALS",
    Home:"Home",
    Services:"Services",
    Portfolio:"Portfolio",
    About:"About",
    Contact:"Contact Us",
    Welcome:" Welcome to Technical For Metal Works And Supplies!",
    Welcom:"Your go-to solution for all your metal needs",
    Work:"See Our Work",
    All:"All",
    Turning: "Lathing Metals",
    Milling:"Milling",
    Welding:"Welding",
    Raw:"Raw Materials",
    Surface:"Surface Grinding",
    CNC:"Lathing CNC",
    Machines:"Machines",
    Abou:"Our expertise lies in metalworking, and we have a team of skilled professionals who are well-versed in various metal fabrication techniques. Whether you need custom designs, precision cutting, welding, or finishing services, we have the knowledge and experience to deliver exceptional craftsmanship. We are committed to meeting your specifications and ensuring the highest quality standards.",
    Us:"Some Stuff About Us",
    Ab:"We have been providing our services as manufacturing and supplying for more than 17 years. We specialize in cement and flat glass factories. The company has extensive experience in maintenance work and cement and flat glass lines.",
    Abb:"Over the years, we have established ourselves as a truste provider of metalworking solutions across various industries. From construction and architecture to automotive and aerospace, our expertise spans a wide range of sectors. We understand the unique requirements of each industry and tailor our products and services to meet their specific needs.",
    Export:"Import & Export",
    Expor:"We have established strong global connections and excel in both import and export activities. By collaborating with trusted partners worldwide, we ensure a seamless flow of metal materials, tools, and equipment. We take pride in sourcing the finest metal products to meet the diverse needs of our valued customers.",
    Supplies:"Factory Supplies",
    Supplie:"With a comprehensive inventory of metal supplies, we offer a convenient one-stop shop for all your metalworking requirements. From raw materials such as steel, aluminum, and copper to specialized tools and machinery, you can rely on us to provide top-notch products to support your projects.",
    Working:"Metal Working",
    Workin:"Our expertise lies in metalworking, and we have a team of skilled professionals who are well-versed in various metal fabrication techniques. Whether you need custom designs, precision cutting, welding, or finishing services, we have the knowledge and experience to deliver exceptional craftsmanship. We are committed to meeting your specifications and ensuring the highest quality standards.",
    Good:"We are Good at",
    Projects:"Our best Products",
    Team:"Meet Our Special Team Members",
    Field:"Contact For Any field",
    More:"Show More",
    Links:"Links",
    msg:"Get in touch with us via email phone or Whatsapp.We are waiting for your call or message",
    Send:"Send",
    Corona:"Corona Gear",
    Argon:"Argon Welding",
    Pipe:"Pipe raw materials",
    Projectss:"Most of Our Products",
    Corners:"Corners Raw Materials",
    CO2:"CO2 Welding",
    Worm:"Worm Gear",
    Straight:"Straight Gear",
    Electric:"Electric Willding",
    screw:"Lathing screw work",
    Stainless:"Stainless material",
    Name:"Name",
    Number:"Number",
    Message:"Message",
    Subject:"Subject",
    mail:"You Email",
    kmr:"Cameroon raw materials",
    coil:"Sheet coil raw materials",
    helical:"Milling helical gears",
    lightening:"Internal lightening milling",
    Column:"Column lathing",
    Chrome:"Chrome gear milling",
    Rack:"Toothed rack milling",

},
  ar: {
    Technical: "الفنية",
    operating: "لتشغيل و توريد المعادن",
    Home:"الرئيسية",
    Services:"الخدمات",
    Portfolio:"أعمالنا",
    About:"من نحن",
    Contact:"تواصل معنا",
    Welcome:"!مرحبا بك فى الفنية لتشغيل و توريد المعادن",
    Welcom:"الحل الأمثل لجميع احتياجاتك المعدنية",
    Work:"أنظر الى أعمالنا",
    All:"الكل",
    Turning: "خراطة معادن",
    Milling:"تفريز",
    Welding:"لحام",
    Raw:"خامات",
    Surface:"تجليخ سطحى",
    CNC:"CNC خراطة ",
    Machines:"المكن",
    Abou:"تكمن خبرتنا في تشغيل وتوريد المعادن، ولدينا فريق من المهنيين المهرة الذين لديهم خبرة جيدة في مختلف تقنيات تصنيع المعادن. سواء كنت بحاجة إلى تصميمات مخصصة، أو قطع دقيق، أو لحام، أو خراطة فلدينا المعرفة والخبرة لتقديم براعة استثنائية. نحن ملتزمون بتلبية مواصفاتك وضمان أعلى معايير الجودة.",
    Us:"بعض المعلومات عنا",
    Ab:"نحن نقدم خدماتنا في مجال التصنيع والتوريد منذ أكثر من 17 عامًا. نحن متخصصون في مصانع الأسمنت والزجاج المسطح. تتمتع الشركة بخبرة واسعة في أعمال الصيانة وخطوط الأسمنت والزجاج المسطح",
    Abb:"على مر السنين، قمنا بتأسيس أنفسنا كمزود موثوق لحلول تشغيل المعادن في مختلف الصناعات. تمتد خبرتنا إلى مجموعة واسعة من القطاعات. نحن نفهم المتطلبات الفريدة لكل صناعة ونصمم منتجاتنا وخدماتنا لتلبية احتياجاتهم الخاصة.",
    Export:"الأستيراد و التصدير",
    Expor:"لقد أنشأنا اتصالات عالمية قوية ونتميز في أنشطة الاستيراد والتصدير. ومن خلال التعاون مع شركاء موثوقين في جميع أنحاء العالم، نضمن التدفق السلس للمواد والأدوات والمعدات المعدنية. نحن نفخر بالحصول على أفضل المنتجات المعدنية لتلبية الاحتياجات المتنوعة لعملائنا الكرام.",
    Supplies:"توريدات",
    Supplie:"من خلال المخزون الشامل من الإمدادات المعدنية، فإننا نقدم متجرًا شاملاً مناسبًا لجميع متطلبات تشغيل المعادن الخاصة بك. بدءًا من المواد الخام مثل الفولاذ والألمنيوم والنحاس وحتى الأدوات والآلات المتخصصة، يمكنك الاعتماد علينا لتوفير منتجات من الدرجة الأولى لدعم مشاريعك.",
    Working:"تشغيل المعادن",
    Workin:"تكمن خبرتنا في تشغيل المعادن، ولدينا فريق من المهنيين المهرة الذين لديهم خبرة جيدة في مختلف تقنيات تصنيع المعادن. سواء كنت بحاجة إلى تصميمات مخصصة، أو قطع دقيق، أو لحام، أو خدمات تشطيب، فلدينا المعرفة والخبرة لتقديم براعة استثنائية. نحن ملتزمون بتلبية مواصفاتك وضمان أعلى معايير الجودة.",
    Good:"نحن متميزين فى",
    Projects:"أفضل منتجاتنا",
    Team:" فريق عملنا المميز",
    Field:"تواصل معنا من أجل أى غرض",
    More:"رؤية المزيد",
    Links:"روابط",
    msg:"تواصل معنا عبر البريد الإلكتروني أو الهاتف أو الواتساب. نحن في انتظار مكالمتك أو رسالتك",
    Send:"ارسال",
    Corona:"ترس كورونا",
    Argon:"لحام أرجون",
    Pipe:"خامة مواسير",
    Projectss:"معظم أعمالنا",
    Corners:"خامات زوايا",
    CO2:"CO2 لحام",
    Worm:"ترس دودة",
    Straight:"ترس عدل",
    Electric:"لحام كهرباء",
    screw :"خراطة عمل قلاووظ",
    Stainless:"خامة أستانلس",
    Name:"الأسم",
    Number:"الرقم",
    Message:"رسالتك",
    Subject:"التخصص",
    mail:"الأيميل",
    kmr:"خامات كمر",
    coil:"خامات لفائف صاج",
    helical:"تفريز تروس حلزونية",
    lightening:"تفريز تفتيح داخلى",
    Column:"خراطة عمدان",
    Chrome:"تفريز ترس كروم",
    Rack:"تفريز جريدة مسننة",

}
};

function updateLanguage() {
  let selectedLang = document.getElementById("language-selector").value;
  let elements = document.querySelectorAll("[data-lang]");
  elements.forEach(function (element) {
    let key = element.getAttribute("data-lang");
    element.innerHTML = lang[selectedLang][key];
  });
}

document
  .getElementById("language-selector")
  .addEventListener("change", updateLanguage);
